// sincos_turns: sin/cos of a phase given in turns, table + polynomial.
//
//   sin_o/cos_o = sin/cos(2*pi * phase/2^PHW) as signed Q2.(OW-2).
//
// Quadrant fold (top 2 phase bits) + piecewise polynomial over the quarter
// turn: 2^SEGW segments, degree-DEG Horner in the ZW-bit normalized
// in-segment offset, coefficients from ROMs generated by
// tools/coeffgen/gen_sincos.py (committed under rtl/common/fn/tables/).
// All truncations are floor (arithmetic shifts), mirrored exactly by the
// golden model. Combinational; pipelining is applied on composition.
//
// Accuracy: <= 2 ulp of 2^-(OW-2) (validated in tests/test_golden_fn.py; see
// the DESIGN.md error budget).
//
// Golden model: host/zetafpga/golden/fn.py::sincos_turns
module sincos_turns #(
    parameter int unsigned PHW = 96,
    parameter int unsigned OW = 64,
    parameter int unsigned SEGW = 10,
    parameter int unsigned DEG = 5,
    parameter int unsigned ZW = 64,
    parameter int unsigned CF = 72,
    parameter int unsigned CW = 80,
    parameter string SIN_ROM = "sincos_s10d5z64o64_sin.mem",
    parameter string COS_ROM = "sincos_s10d5z64o64_cos.mem",
    localparam int unsigned QW = PHW - 2
) (
    // Phase bits below the SEGW+ZW window are quantization by design.
    // verilator lint_off UNUSEDSIGNAL
    input  logic [PHW-1:0]       phase,
    // verilator lint_on UNUSEDSIGNAL
    output logic signed [OW-1:0] sin_o,
    output logic signed [OW-1:0] cos_o
);

  initial begin
    assert (QW >= SEGW + ZW)
    else $fatal(1, "sincos_turns: PHW too small for SEGW+ZW");
  end

  localparam int unsigned NCOEF = (1 << SEGW) * (DEG + 1);
  localparam int unsigned ACCW = CW + 2;  // Horner accumulator
  localparam int unsigned SHIFT = CF - (OW - 2);

  logic signed [CW-1:0] sin_rom [0:NCOEF-1];
  logic signed [CW-1:0] cos_rom [0:NCOEF-1];

  initial begin
    $readmemh(SIN_ROM, sin_rom);
    $readmemh(COS_ROM, cos_rom);
  end

  logic [1:0] quadrant;
  logic [SEGW-1:0] seg;
  logic [ZW-1:0] z;

  assign quadrant = phase[PHW-1-:2];
  assign seg      = phase[QW-1-:SEGW];
  assign z        = phase[QW-SEGW-1-:ZW];

  logic signed [ACCW-1:0] sacc, cacc;
  logic signed [ACCW+ZW:0] sprod, cprod;

  always_comb begin
    sacc = ACCW'(sin_rom[seg*(DEG+1)+DEG]);
    cacc = ACCW'(cos_rom[seg*(DEG+1)+DEG]);
    for (int k = int'(DEG) - 1; k >= 0; k--) begin
      sprod = sacc * $signed({1'b0, z});
      cprod = cacc * $signed({1'b0, z});
      sacc  = ACCW'(sin_rom[seg*(DEG+1)+unsigned'(k)]) + ACCW'(sprod >>> ZW);
      cacc  = ACCW'(cos_rom[seg*(DEG+1)+unsigned'(k)]) + ACCW'(cprod >>> ZW);
    end
  end

  // Quarter-wave results (non-negative on [0, 1/4]) then quadrant map.
  logic signed [OW-1:0] s0, c0;

  assign s0 = OW'(sacc >>> SHIFT);
  assign c0 = OW'(cacc >>> SHIFT);

  always_comb begin
    unique case (quadrant)
      2'd0: begin sin_o = s0;  cos_o = c0;  end
      2'd1: begin sin_o = c0;  cos_o = -s0; end
      2'd2: begin sin_o = -s0; cos_o = -c0; end
      2'd3: begin sin_o = -c0; cos_o = s0;  end
    endcase
  end

endmodule
